name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Xcode
        uses: actions/setup-xcode@v2.4.0
        with:
          xcode-version: "13.0"

      - name: Build
        run: xcodebuild -scheme MyProject -destination 'platform=iOS Simulator,name=iPhone 12' build test
