name: Swift

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Swift
        run: |
          wget https://swift.org/builds/swift-5.8.0-release/xcode/swift-5.8.0-RELEASE/swift-5.8.0-RELEASE-osx.pkg
          sudo installer -pkg swift-5.8.0-RELEASE-osx.pkg -target /
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
