# This workflow will test and build a SWIFT project
# Using Package.swift at hrvm/hrv_standalone_watch_app/Package.swift

# Path: .github/workflows/swift.yml

# This workflow will test and build a SWIFT project

name: Swift

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./hrvm/hrv_standalone_watch_app
        run: swift build
      - name: Test
        working-directory: ./hrvm/hrv_standalone_watch_app
        run: swift test
